#ifndef ENUMERATION
#define ENUMERATION

enum	NIVEAUJEU{ FAIBLE = 1, MOYEN, FORT };
enum	NOMJOUEUR{ PERSONNE, ORDI, HUMAIN };
enum	COULEURBOULE{ BLANC = 0, NOIR };
enum	PERIODEJEU{ ATTENTE, ORDIJOUE, HUMAINJOUE };
enum	ETATCASE{ CVIDE, CHUMAIN, CORDI };
enum	CODEFIN{ CONTINUE, ORDIFIN, HUMAINFIN, PARTIENULLE, ARRETPARTIE, HUMAINERREUR };

#endif // ENUMERATION

